# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-build-pr

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        wabt-version: [1.0.36]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use WABT ${{ matrix.wabt-version }}
      uses: mwilliamson/setup-wabt-action@v3
      with:
        wabt-version: ${{ matrix.wabt-version }}

    - name: Download Dependencies
      run: bash ./scripts/download.sh vibrato.js

    - name: Build WASM Modules
      run: bash ./scripts/build-wa.sh

    - name: NPM build/test
      run: |
        npm ci
        npm run build --if-present
        npm test
